version: '3.3'

services:
  silkdb:
    image: mysql:5.7
    restart: always
    container_name: mysql_silkroad
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "silkroad"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    
  api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: nest_silkroad
    depends_on:
      - silkdb
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - /app/node_module
      - .:/app
    environment:
      - DATABASE_URL="mysql://root:password@silkdb:3306/silkroad"
